VERSION = 0.2.0
QT -= gui
#CONFIG += debug

PLUGIN_QML_TARGET_BASE_PATH = $$[QT_INSTALL_IMPORTS]/Sharing/plugins/
SHARINGD_PLUGIN_PATH=/usr/lib/sharing/plugins

DEFINES += QML_TARGET_BASE_PATH=\\\"$$PLUGIN_QML_TARGET_BASE_PATH\\\"
DEFINES += SHARINGD_PLUGIN_PATH=\\\"$$SHARINGD_PLUGIN_PATH\\\"

PROJECT_NAME = sharing
BASEDIR = $$system(pwd)

DISTDIR = $${BASEDIR}/$${PROJECT_NAME}-$${VERSION}
TSDIR = $${DISTDIR}/ts
